// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKB9zd1TtnNYQxkijEk_0xop5MquutEGg',
    appId: '1:505699465496:web:e51a179ff063ebab41c66d',
    messagingSenderId: '505699465496',
    projectId: 'the-list-ac697',
    authDomain: 'the-list-ac697.firebaseapp.com',
    storageBucket: 'the-list-ac697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ebnR9y4-H3f0gotIi0QzjfSL_tt_89w',
    appId: '1:505699465496:android:ba9f2fcece88cbdb41c66d',
    messagingSenderId: '505699465496',
    projectId: 'the-list-ac697',
    storageBucket: 'the-list-ac697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmh3j5SlOwR3zHQD7LSBcjPdU1RfwB_F8',
    appId: '1:505699465496:ios:ed213e98d175fd5641c66d',
    messagingSenderId: '505699465496',
    projectId: 'the-list-ac697',
    storageBucket: 'the-list-ac697.appspot.com',
    iosClientId: '505699465496-dtd9b90cr0m8m40mnllr90gq9hbmkno9.apps.googleusercontent.com',
    iosBundleId: 'dev.ctrle.thelist.theList',
  );
}
